package com.queueless.backend.notification;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_REJECTED,
    ORDER_CANCELLED,
    PICKUP_SLOT_REQUESTED,
    PICKUP_SLOT_ACCEPTED,
    PICKUP_SLOT_REJECTED,
    PICKUP_SLOT_COUNTER_PROPOSED,
    PICKUP_SLOT_CUSTOMER_ACCEPTED,
    PICKUP_SLOT_CUSTOMER_REJECTED,
    ORDER_READY_FOR_PICKUP,
    ORDER_COLLECTED,
    COMPLAINT_SUBMITTED,
    COMPLAINT_REVIEWED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REINSTATED,
    SHOP_SUSPENDED,
    SHOP_REINSTATED
}
